### ISSUE TITLE
Unused variable `treeID`

### ISSUE THREAD

**Issue by XichengTong** [jackhax/supply-chain-security#1]
https://github.com/jackhax/supply-chain-security/blob/719bff5da8c71e2d3e25ecc9cce2a929bf307f29/main.py#L104
 Variable `treeID` is assigned to but never used in this function.

**Comment by jackhax** [comment]
Removed unused variable in commit [a6b95f7](https://github.com/jackhax/supply-chain-security/commit/a6b95f79587a4fc9fe5a6791d0dc1b567fdab815)
