### ISSUE TITLE
Local variable `e` is assigned to but never used

### ISSUE THREAD

**Issue by XichengTong** [jackhax/supply-chain-security#2]
https://github.com/jackhax/supply-chain-security/blob/719bff5da8c71e2d3e25ecc9cce2a929bf307f29/merkle_proof.py#L158
Remove assignment to unused variable `e`

**Comment by jackhax** [comment]
Fixed in commit [bdcd734](https://github.com/jackhax/supply-chain-security/commit/bdcd734a265a73ad0c45797d610f504bb053864c) by utilizing the variable e when debug=true
