### ISSUE TITLE
Hardcoded URLs

### ISSUE THREAD

**Issue by XichengTong** [jackhax/supply-chain-security#3]
https://github.com/jackhax/supply-chain-security/blob/719bff5da8c71e2d3e25ecc9cce2a929bf307f29/main.py#L31
The URL for the Rekor API is hardcoded multiple times throughout the code. This could be made a constant at the top of the script for easier maintenance.

**Comment by jackhax** [comment]
Fixed issue by creating a global variable for API that loads the API string from a config file
